### PR TITLE
Fix issue in java client where IOExceptions result in NPE

### PR DESCRIPTION
**Pull request by jakeaccedo**
When the client gets an IOException from the request, the response error is null.
This results in a NPE as `response.getError()` returns null.

This should probably be handled differently back where the IOException is thrown, maybe don't pass the exception back as the response to start with.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @jakeaccedo,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by elilevi0907** [comment]
@noamtamim, please see the above from Accedo.

**Comment by noamtamim** [comment]
@jakeaccedo, (how) did you verify this fix?

**Comment by tan-tan-kanarek** [comment]
Approved, but the pull-request should be against Naos-14.19.0.
Please pull against the right branch and I'll merge it.

**Comment by jakeaccedo** [comment]
> @jakeaccedo, (how) did you verify this fix?

@noamtamim 
Checked in our case where we were experiencing SSL issues while accessing through VPN, these issues were being 'hidden' as a nullpointer exception was being thrown while trying to handle the transport layer exception.

With this fix, the proper transport layer exception is passed back through error handling and we are able to log it

**Comment by noamtamim** [comment]
@jakeaccedo thank you for this fix 👍

**Pull request merged**
