### PR TITLE
Update Php5Zend client generator [Dirty patches from php53]

### PR DESCRIPTION
**Pull request by sunnyagain**
I am not sure whether this should be accepted or not,
But current generated Lib does not work with json at all.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @sunnyagain,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by tan-tan-kanarek** [comment]
Generated lab should work with XML, there is no reason for it to work with JSON.

**Comment by sunnyagain** [comment]
@tan-tan-kanarek Agreed just wanted to make it similar to php5 lab which works with JSON / PHP / XML format data.

**Comment by tan-tan-kanarek** [comment]
The PHP5 lib is used by OVP batch system and therefore its performance matters.
In some of community edition installations the OVP is installed without its XML serializing PHP extension which causing the XML serialization to be more expensive (performance wise), in such cases these installations can choose to use the JSON format, in the Zend library that used mostly by UI components it doesn't matter, and the XML sterilizer of the OTT is server doesn't have that same performance penalty.

**Pull request closed without merging**
