### PR TITLE
SUP-12156:converting xml to utf8

### PR DESCRIPTION
**Pull request by ravitshalem**

### CODE REVIEW

**Comment by tan-tan-kanarek** [comment]
Thank you for your contribution.
We assume that Kaltura server responsed are already UTF-8.
Could you tell me what API call didn't return as UTF-8 and required this change?

**Comment by ravitshalem** [comment]
API: cuepoint::get
for example- cuepoint id=0_1yrz8dce on entry id=0_ll8l7l22
There is a question mark in the title of this cuepoint which causes a parse error.
this error happens when doing $xml = new SimpleXMLElement($xmlData);
on the the php zend client

**Comment by jessp01** [comment]
The cue_point table's default charset is already UTF-8 and yet, if you run:
```
mysql> select * from cue_point where id='0_1yrz8dce'\G
```
you'll see the last char is not correctly interpolated, so I don't think the problem is with the Zend client.
Even if you force UTF-8 like so:
```
mysql> select CONVERT(name USING utf8) from cue_point where id='0_1yrz8dce'\G
```
the result is the same.

**Comment by jessp01** [comment]
calling mb_convert_encoding($xml,'UTF-8', 'UTF-8') may make the unrecognised char disappear but it's not really a solution, IMHO.
I say: garbage in? garbage out! but if we really want to try to be smarter than the user [not always recommendable], we should discard such chars at the insertion, not during retrieval.

**Comment by jessp01** [comment]
@ravitshalem - in light of https://github.com/kaltura/server/pull/6254/files, let's close this one.

**Pull request closed without merging**
