### PR TITLE
add ability to mark services and actions as beta

### PR DESCRIPTION
**Pull request by noam-arad**

### CODE REVIEW

**Comment by tan-tan-kanarek** [comment]
Testme and testmeDoc are deprecated.
@jessp01, @zoharbabin, please consider supporting this also in the new documentation and console.

**Comment by zoharbabin** [comment]
Just wondering - when do we have such scenarios?
And what will we mean by marking an action as beta? will it mean that this action is likely to change? will it mean that it's not stable and should be avoided?

@noam-arad / @tan-tan-kanarek

**Comment by jessp01** [comment]
My two cents: an example for a service that should have been annotated as "experimental" [I think that's a better term than "beta" in this context] is the "analytics" service [AKA Kanalony] which we've since deprecated altogether in favour of the Kava service.

**Comment by noam-arad** [comment]
What we were trying to do here is to develop some API, set it out to the public but let them know we are not yet willing to commit to this API, that it will exist, that it will still function the same way, that the parameters won't change etc'. This can help us develop features that are not only in the backend and enable us to test these APIs separately from the other components while we develop them.
experimental could be another name for this.

**Comment by zoharbabin** [comment]
Ok. Thx.

**Pull request merged**
