### PR TITLE
feat(node2): add support for Buffer instead of filepaths

### PR DESCRIPTION
**Pull request by bcluyse**
In our project we need support for uploading a file in chunks without having to split the file in multiple parts.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @bcluyse,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
Hello @bcluyse,

Thank you for your contribution,
Kindly add a test here: https://github.com/kaltura/clients-generator/blob/Orion-15.3.0/tests/ovp/node2/test so that we may verify everything works correctly.

Once it passes, we'll able to merge and release a new `kaltura-client` NPM  (https://www.npmjs.com/package/kaltura-client)

Thanks again,

**Comment by jessp01** [comment]
Hi @bcluyse,

With the media.js code as it is in your branch, execution with NodeJS 6 fails (see https://www.travis-ci.org/kaltura/KalturaGeneratedAPIClientsNodeJS/builds/562049610)

Now, NodeJS 6 is quite old and is considered obsolete, I'll grant you but since these revisions make it run correctly on all tested versions (6, 8 and 10), please adjust your code based on these commits I made to the test repo:
https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/commit/1a723e956d235cffa48e426b32c105fad2e9b4d4
https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/commit/22755453761ca43ba38072ede0f75f04f41a8ab8

Thanks,

**Comment by bcluyse** [comment]
Should be fixed now, I was not aware the tests had to run on Node 6.
Thanks for the help.

**Comment by jessp01** [comment]
Yeap. We do not recommend using such old versions by any means but customers do have them..
Looks good now. We'll wait for the nightly run but I'm all for merging following that.

**Comment by jessp01** [comment]
CI passed: 
https://www.travis-ci.org/kaltura/KalturaGeneratedAPIClientsNodeJS/builds/562548365

**Pull request merged**
