### PR TITLE
Add Python 3 support to Python bindings

### PR DESCRIPTION
**Pull request by ccorbacho**
Add support for using the Kaltura Python bindings on Python 3.

As the poster library this was using before is not compatible with Python 3 (and has been unmaintained for 7 years), it is replaced with requests, which is Python 2 and 3 compatible.

For now, compatibility with Python 2 is maintained (the bindings can now run on 2 & 3), but only for 2.6 and 2.7 - the features needed for compatibility with Python 3 are not available in older versions, nor does the requests library suppose those older versions; but in 2017, that is a reasonable trade off for only having one code base to support.

### CODE REVIEW

**Comment by jessp01** [comment]
Hi @ccorbacho,

Very nice work! Tested with Both Python 2.7.6 and 3.4.3 and it works well.
Note however, that for the requests module needs to be of version 2.4.2 and above is needed for your code to work, otherwise, one gets:
```
Traceback (most recent call last):
  File "/opt/kaltura/web/content/clientlibs/python.new/KalturaClient/tests/test_functional.py", line 67, in test_addmedia
    mediaEntry = self.client.media.addFromUploadedFile(mediaEntry, uploadTokenId)
  File "/opt/kaltura/web/content/clientlibs/python.new/KalturaClient/Plugins/Core.py", line 58163, in addFromUploadedFile
    resultNode = self.client.doQueue()
  File "/opt/kaltura/web/content/clientlibs/python.new/KalturaClient/Client.py", line 334, in doQueue
    postResult = self.doHttpRequest(url, params, files)
  File "/opt/kaltura/web/content/clientlibs/python.new/KalturaClient/Client.py", line 287, in doHttpRequest
    url, params, files, self.requestHeaders, requestTimeout)
  File "/opt/kaltura/web/content/clientlibs/python.new/KalturaClient/Client.py", line 269, in openRequestUrl
    e, KalturaClientException.ERROR_CONNECTION_FAILED)
KalturaClientException: request() got an unexpected keyword argument 'json' (-4)
```

I don't mind depending on 2.4.2 and above but can you please update setup.py and the README accordingly?

**Comment by jessp01** [comment]
Also, would you mind pulling against the Lynx-12.15.0 branch? Lynx-12.14.0 was released as stable yesterday. Thanks again!

**Comment by ccorbacho** [comment]
@jessp01 All changes should be on here now. I'm testing locally with Python 3.5, so I know this works there as well. Not sure how you want to handle the CI side - I would suggest a dedicated job for Python 3 unit tests on travis (similar to how you have one for PHP 5.3 and 5.5).

**Comment by jessp01** [comment]
Thanks, @ccorbacho, looks good:)
CI - yes, once merged, I'll update https://github.com/kaltura/KalturaGeneratedAPIClientsPython/blob/master/.travis.yml so that the test suite will run with Python 2.7, 3.4 and, for good measure, 3.5 too:)
There is a nightly process that generates the client libs from the latest branch of the clients-generator repo and pushes the results to https://github.com/kaltura/KalturaGeneratedAPIClients*

Thanks again.

**Comment by jessp01** [comment]
Sorry, @ccorbacho, one more fix is needed. In setup.py, please replace:
```
from distutils.core import setup
```
with:
```
from setuptools import setup
```
distutils does not support install_requires, setuptools does.

Thanks,

**Comment by ccorbacho** [comment]
@jessp01 Good catch - should be fixed now.

**Pull request merged**
