### PR TITLE
Fix: Xcode 13.3.1 Sendable class exception

### PR DESCRIPTION
**Pull request by shaharukhs**
'`Sendable`' class '`ApiException`' cannot inherit from another class other than '`NSObject`'

Screen Shot 2022-04-13 at 11 11 45 AM

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @shaharukhs,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by shaharukhs** [comment]
> Hi @shaharukhs, Thank you for contributing this pull request! Please sign the Kaltura CLA so we can review and merge your contribution. Learn more at http://bit.ly/KalturaContrib

Done, signed CLA.

**Comment by jessp01** [comment]
Hi @shaharukhs ,

Please resubmit your pull against the current branch. If you look at the diff on this one, you'll see it includes many changes that were not made by you and do not pertain to the issue you're trying to address.

Thanks,

**Comment by shaharukhs** [comment]
> Hi @shaharukhs ,
> 
> Please resubmit your pull against the current branch. If you look at the diff on this one, you'll see it includes many changes that were not made by you and do not pertain to the issue you're trying to address.
> 
> Thanks,

https://github.com/kaltura/clients-generator/pull/792 resubmitted to current branch.
Thanks.

**Pull request closed without merging**
